name: bhashaverse_debug
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  record: ^4.4.4
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  audio_waveforms: ^1.0.0
  dio: ^5.1.1
  lottie: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/lottie/

