class LanguageCode {
  static const Map<String, String> languageCode = {
    'en': 'English',
    'hi': 'Hindi',
    'mr': 'Marathi',
    'bn': 'Bangla',
    'pa': 'Punjabi',
    'gu': 'Gujarati',
    'or': 'Odia',
    'ta': 'Tamil',
    'te': 'Telugu',
    'kn': 'Kannada',
    'ur': 'Urdu',
    'doi': 'Dogri',
    'ne': 'Nepali',
    'si': 'Sinhala',
    'sa': 'Sanskrit',
    'as': 'Assamese',
    'mai': 'Maithili',
    'bho': 'Bhojpuri',
    'ml': 'Malayalam',
    'raj': 'Rajasthani',
    'brx': 'Bodo',
    'mni': 'Manipuri',
    'ks': 'Kashmiri',
    'kok': 'Konkani',
    'sd': 'Sindhi',
    'sat': 'Santali',
  };
}
